<a href="https://colab.research.google.com/github/Vigneshx1/DHV/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(len(array_1d))
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(len(array_2d))
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])
print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(len(array_3d))


(5,)
5
1
5
(2, 3)
6
2
2
(2, 2, 3)
12
3
2


In [3]:
a_example = np.arange(1, 10, 2)
print(a_example)
randint_example = np.random.randint(1, 100, size=(3, 3))
print(randint_example)
rand_example = np.random.rand(2, 3)
print(rand_example)
lspace_example = np.linspace(1, 10, num=5)
print(lspace_example)
ones_example = np.ones((2, 3))
print(ones_example)
zeros_example = np.zeros((3, 2))
print(zeros_example)
diag_example = np.diag([1, 2, 3])
print(diag_example)

[1 3 5 7 9]
[[93 81 57]
 [95 12 39]
 [88 94 82]]
[[0.78975369 0.76929742 0.50090362]
 [0.00674678 0.54976782 0.51723551]]
[ 1.    3.25  5.5   7.75 10.  ]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [4]:

marks= np.random.randint(0, 101, size=10)
print(marks)

[38 60 56 69 84 70 69  1 81 38]


In [7]:
f_marks= marks[marks < 30]
print(f_marks)


[1]


In [6]:
print(f_marks)
pmarks=marks[marks>=30]
print(pmarks)
rows = 3
cols = 4
random_2d_array = np.random.rand(rows, cols)
print(random_2d_array)


[1]
[38 60 56 69 84 70 69 81 38]
[[0.90328199 0.05403441 0.59894875 0.762566  ]
 [0.66463444 0.0956257  0.89427572 0.83871741]
 [0.38920741 0.60329522 0.39068429 0.44860363]]
